### ISSUE TITLE
Transitiivisuusesimerkissä taitaa olla typo

### ISSUE THREAD

**Issue by jrutila** [avoimet-oppimateriaalit-ry/vapaa-matikka-vol1#1]
TEORIA_luku_ja_relaatio.tex Rivi 77:
§ Jos $t=3$ ja toisaalta $y=t$, niin silloin välttämättäkin transitiivisuuden perusteella $y=t$.

Pitäisi varmaankin olla:

§ Jos $t=3$ ja toisaalta $y=t$, niin silloin välttämättäkin transitiivisuuden perusteella $y=3$.

**Comment by JoonasD6** [comment]
Korjattu; kiitos huomiosta. Päivitykset tulevat seuraavaan uuden opsin versioon. :)
